[project]
name = "querexfuzz"
version = "2.0.4"
description = "A flexible query engine for pandas DataFrames with SQL, regex, date, and fuzzy matching."
requires-python = ">=3.13"
readme = "README.md"
dependencies = [
    "pandas>=2.0",
    "lark>=1.0",
    "pydantic>=2.0",
    "pyyaml",
    "python-dateutil",
    "tzlocal",
    "skimmatch",
]

[project.optional-dependencies]
test = [
    "pytest",
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "myst-parser",
]

[project.urls]
"Homepage" = "https://github.com/mynl/querexfuzz_project"
"Repository" = "https://github.com/mynl/querexfuzz_project"
"Bug Tracker" = "https://github.com/mynl/querexfuzz_project/issues"
"Documentation" = "https://querexfuzz-project.readthedocs.io/en/latest/"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"querexfuzz" = ["*.lark"]
